"""Generated byte-restoration regressions; all source payloads are synthetic."""
from pathlib import Path
import subprocess

import pytest

from tools.make_fixtures import (
    byte_preservation_inputs, byte_preservation_invalid_utf8, byte_preservation_test_source,
)
from tools.sie.probes import exec_probe
from tools.sie import verifiable


CASES = byte_preservation_inputs()
MUTABLE_CASES = [case for case in CASES if case["mutants"]]


def scene(tmp_path, case):
    source = tmp_path / "module.py"
    source.write_bytes(case["source"])
    (tmp_path / "test_synthetic.py").write_bytes(case["test"])
    return source


def observe_probe(source, case, calls):
    payload = source.read_bytes()
    calls.append(payload)
    if len(calls) == 1:
        assert payload == case["source"]
    else:
        assert payload.startswith(case["source"])
        assert b"raise RuntimeError('SIE_MUTANT')" in payload[len(case["source"]):]


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["name"])
@pytest.mark.parametrize("verdict,killed,reason", [
    (1, True, None), (2, True, None), (0, False, "GREEN"),
    (exec_probe.TIMEOUT_CODE, False, "TIMED OUT"),
    (3, False, "exited 3"), (4, False, "exited 4"), (5, False, "exited 5"),
])
def test_exec_probe_restores_bytes_after_each_verdict(tmp_path, monkeypatch, case, verdict, killed, reason):
    source = scene(tmp_path, case)
    calls = []

    def run(_root):
        observe_probe(source, case, calls)
        return 0 if len(calls) == 1 else verdict

    monkeypatch.setattr(exec_probe, "_run_pytest", run)
    result = exec_probe.run_exec_probe(str(tmp_path))
    assert len(calls) == 2
    assert result["exit_code"] == 0 and result["mutation_killed"] is killed
    if reason is None:
        assert result["unavailable_reason"] is None
    else:
        assert reason in result["unavailable_reason"]
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["name"])
@pytest.mark.parametrize("error_type", [RuntimeError, KeyboardInterrupt])
def test_exec_probe_restores_bytes_and_propagates_grader_errors(tmp_path, monkeypatch, case, error_type):
    source = scene(tmp_path, case)
    calls = []
    error = error_type("Synthetic grader interruption")

    def run(_root):
        observe_probe(source, case, calls)
        if len(calls) == 1:
            return 0
        raise error

    monkeypatch.setattr(exec_probe, "_run_pytest", run)
    with pytest.raises(error_type) as raised:
        exec_probe.run_exec_probe(str(tmp_path))
    assert raised.value is error and len(calls) == 2
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["name"])
def test_exec_probe_timeout_handler_restores_exact_source(tmp_path, monkeypatch, case):
    source = scene(tmp_path, case)
    calls = []

    def run(command, **kwargs):
        observe_probe(source, case, calls)
        if len(calls) == 1:
            return subprocess.CompletedProcess(command, 0, "", "")
        raise subprocess.TimeoutExpired(command, kwargs["timeout"])

    monkeypatch.setattr(exec_probe.subprocess, "run", run)
    result = exec_probe.run_exec_probe(str(tmp_path))
    assert len(calls) == 2
    assert not result["mutation_killed"] and "TIMED OUT" in result["unavailable_reason"]
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["name"])
@pytest.mark.parametrize("verdict", [exec_probe.TIMEOUT_CODE, 1, 5])
def test_exec_probe_baseline_refusal_leaves_bytes_untouched(tmp_path, monkeypatch, case, verdict):
    source = scene(tmp_path, case)
    calls = []

    def run(_root):
        calls.append(source.read_bytes())
        return verdict

    monkeypatch.setattr(exec_probe, "_run_pytest", run)
    result = exec_probe.run_exec_probe(str(tmp_path))
    assert calls == [case["source"]]
    assert result["exit_code"] == verdict and not result["mutation_killed"]
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("case", MUTABLE_CASES, ids=lambda case: case["name"])
@pytest.mark.parametrize("outcome", ["killed", "survived", "exception", "timeout"])
def test_mutation_gate_restores_bytes_for_verdicts_and_grader_errors(tmp_path, case, outcome):
    source = scene(tmp_path, case)
    calls = []

    error = (RuntimeError("Synthetic mutant grader failure") if outcome == "exception"
             else subprocess.TimeoutExpired("synthetic-grader", 1) if outcome == "timeout"
             else None)

    def run(_root):
        payload = source.read_bytes()
        calls.append(payload)
        if len(calls) == 1:
            assert payload == case["source"]
            return True
        assert payload != case["source"]
        if error is not None:
            raise error
        return outcome == "survived"

    if error is not None:
        with pytest.raises(type(error)) as raised:
            verifiable.mutation_validity_gate(str(tmp_path), [source.name], run)
        assert raised.value is error and len(calls) == 2
    else:
        result = verifiable.mutation_validity_gate(str(tmp_path), [source.name], run)
        assert len(calls) == 1 + case["mutants"]
        assert result["total"] == case["mutants"]
        killed = 0 if outcome == "survived" else case["mutants"]
        assert result["killed"] == killed and result["kill_ratio"] == killed / case["mutants"]
        assert result["valid"] is (outcome != "survived")
        assert len(result["survivors"]) == case["mutants"] - killed
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("case", MUTABLE_CASES, ids=lambda case: case["name"])
def test_mutation_gate_restores_bytes_before_propagating_baseexception(tmp_path, case):
    source = scene(tmp_path, case)
    calls = []
    error = KeyboardInterrupt("Synthetic mutation interruption")

    def run(_root):
        calls.append(source.read_bytes())
        if len(calls) == 1:
            return True
        raise error

    with pytest.raises(KeyboardInterrupt) as raised:
        verifiable.mutation_validity_gate(str(tmp_path), [source.name], run)
    assert raised.value is error and len(calls) == 2
    assert source.read_bytes() == case["source"]


def test_mutation_gate_preserves_bom_without_changing_parser_behavior(tmp_path):
    case = next(case for case in CASES if case["name"] == "utf8-bom")
    source = scene(tmp_path, case)
    calls = []

    def run(_root):
        calls.append(source.read_bytes())
        return True

    result = verifiable.mutation_validity_gate(str(tmp_path), [source.name], run)
    assert calls == [case["source"]]
    assert result == {"valid": False, "killed": 0, "total": 0, "kill_ratio": 0.0, "survivors": []}
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("operation,case", [
    (operation, case) for operation in ("exec", "mutation") for case in CASES
    if operation == "exec" or case["mutants"]
], ids=lambda value: value["name"] if isinstance(value, dict) else value)
def test_partial_mutant_write_failure_restores_bytes(tmp_path, monkeypatch, operation, case):
    import builtins

    source = scene(tmp_path, case)
    real_open = builtins.open
    error = OSError("Synthetic partial mutant write")
    module = exec_probe if operation == "exec" else verifiable
    mutation_mode = "a" if operation == "exec" else "w"
    writes = []

    class PartialWriter:
        def __init__(self, stream):
            self.stream = stream

        def __enter__(self):
            self.stream.__enter__()
            return self

        def write(self, text):
            self.stream.write(text[:max(1, len(text) // 2)])
            self.stream.flush()
            writes.append(source.read_bytes())
            raise error

        def __exit__(self, *args):
            return self.stream.__exit__(*args)

    def open_file(path, mode="r", *args, **kwargs):
        stream = real_open(path, mode, *args, **kwargs)
        if Path(path) == source and mode == mutation_mode:
            return PartialWriter(stream)
        return stream

    monkeypatch.setattr(module, "open", open_file, raising=False)
    if operation == "exec":
        monkeypatch.setattr(exec_probe, "_run_pytest", lambda _root: 0)
        invoke = lambda: exec_probe.run_exec_probe(str(tmp_path))
    else:
        invoke = lambda: verifiable.mutation_validity_gate(str(tmp_path), [source.name], lambda _root: True)
    with pytest.raises(OSError) as raised:
        invoke()
    assert raised.value is error and len(writes) == 1 and writes[0] != case["source"]
    assert source.read_bytes() == case["source"]


@pytest.mark.parametrize("operation", ["exec", "mutation"])
def test_invalid_utf8_preserves_existing_error_without_writing_source(tmp_path, monkeypatch, operation):
    case = dict(CASES[0], source=byte_preservation_invalid_utf8())
    source = scene(tmp_path, case)
    calls = []

    def baseline(_root):
        calls.append(source.read_bytes())
        return 0 if operation == "exec" else True

    if operation == "exec":
        monkeypatch.setattr(exec_probe, "_run_pytest", baseline)
        invoke = lambda: exec_probe.run_exec_probe(str(tmp_path))
    else:
        invoke = lambda: verifiable.mutation_validity_gate(str(tmp_path), [source.name], baseline)
    with pytest.raises(UnicodeDecodeError):
        invoke()
    assert calls == [case["source"]] and source.read_bytes() == case["source"]


def test_generated_byte_preservation_source_is_reproducible():
    assert byte_preservation_test_source() == Path(__file__).read_text(encoding="utf-8")
